---

- hosts: all
  become: true
  pre_tasks:

  - name: update repos (Debian)
    tags: always
    apt:
      update_cache: true
    changed_when: false
    when: ansible_distribution in ["Ubuntu", "Debian", "LMDE"]

  - name: update repos (RedHat/Fedora)
    tags: always
    dnf:
      update_cache: true
    changed_when: false # force to show not as changed
    when: ansible_distribution in ["Fedora", "Red Hat"]

- hosts: all
  become: true
  roles:
    - base

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: routers
  become: true
  roles:
    - routers
